### ISSUE TITLE
Error: Cannot find module './img/pin.png'

### ISSUE THREAD

**Issue by CSMR-DB** [mariusandra/pigeon-marker#1]
```
import React, { Component } from "react";
import Map from "pigeon-maps";
import Marker from "pigeon-marker";

const PigeonMaps = () => (
    <div>
        <Map center={[50.879, 4.6997]} zoom={12} width={600} height={400}>
            <Marker
                anchor={[50.874, 4.6947]}
                payload={1}
                onClick={({ event, anchor, payload }) => {}}
            />
        </Map>
    </div>
);

export default PigeonMaps;

```

Results in the console spewing out: 

```
Error: Cannot find module './img/pin.png'
modules-runtime.js:241:12
```

This is using `React 16.3.1` on `Node 8.4.0`

I would prefer not even using the PNG's, being able to make my own markers as either an SVG element or just a plain HTML element to have the option to style it according to theme. Is this possible? And how would I go about resolving said error?

**Comment by mariusandra** [comment]
Hey, then you should make your own marker :). This `pigeon-marker` library is just a sample implementation of a widget. Look at the code and customize as needed, it should be fairly straightforward.

Cheers!
