### ISSUE TITLE
Remove files that is not used by end user from npm repo

### ISSUE THREAD

**Issue by avasuro** [mariusandra/pigeon-marker#11]
### Issue

if pigeon-marker is used together with [parcel](https://parceljs.org/), [parcel-plugin-eslint](https://www.npmjs.com/package/parcel-plugin-eslint) and [eslint v7](https://www.npmjs.com/package/eslint/v/7.13.0) - parcel fails to build the bundle, because of bad .eslintrc file in your library (it requires eslint-config-standard and eslint-config-node to be insalled, but they are devDependencies, so not installed on end user machine).

### Solution
It is good practice to exclude such files like .eslintrc, .gitignore and other "utility" files from npm repo to prevent such issues and reduce npm package size.

To do that, could you please add .npmignore file to the root of your project, and add the following to it:
```
node_modules
.eslintrc
.gitignore
docs
demo
src
.babelrc
build.js
webpack.config.js
...any other files that are not required by end-user?
```

Thank you in advance.

**Comment by mariusandra** [comment]
This project is now deprecated by pigeon-maps 0.17 itself, which includes a Marker component
