### ISSUE TITLE
Possible to provide own pin images/skip import

### ISSUE THREAD

**Issue by albinekb** [mariusandra/pigeon-marker#3]
Hi! 

https://github.com/mariusandra/pigeon-marker/blob/master/src/index.js#L4-L7
These lines makes it so you need to have your bundler handle .png imports, would it be possible to swap these out for inline SVG or to have an option for the user to provide own markers and not require .png import?

**Comment by albinekb** [comment]
I just noticed how simple it is to make my own marker.. awesome.

**Comment by willfurnell** [comment]
@albinekb How did you go about it?

**Comment by albinekb** [comment]
```js
import { MapMarker } from 'mdi-material-ui'
const Marker = ({ anchor, left, top }) => {
  return (
    <div style={{ position: 'absolute', left, top }}>
      <div style={{ transform: 'translate(-50%,-50%)', left: '50%', top: '0%', position: 'absolute' }}>
        <MapMarker style={{ width: '48px', height: '48px', color: '#145869' }} />
      </div>
    </div>
  )
}
```

then use it:
```
    <Map
   
      >
        <Marker anchor={latLng} payload={1} onClick={({ event, anchor, payload }) => {}} />
      </Map>
```
