### ISSUE TITLE
Can I change color a marker

### ISSUE THREAD

**Issue by WCChimiiz** [mariusandra/pigeon-marker#4]
Can I change color a marker

**Comment by einarjegorov** [comment]
At least by looking a the source, the marker seems to be a plain PNG file. I see two ways:

- Fork and replace the marker image with your own
- Contribute! Add `marker` as a prop to `<Marker>` component

**Comment by romandecker** [comment]
It's pretty easy to just create your own marker with whatever file you choose. Here's an example using an svg as a marker:

```ts
import * as React from 'react';
import { LatLng } from 'pigeon-maps';
import { MapMarkerIcon } from '../../../common/components/icons';

interface Props {
    anchor: LatLng;

    // these are automatically set by the surrounding Map component from pigeon-map
    left?: number;
    top?: number;
}

const PIN_CENTER = {
    x: 15,
    y: 31,
};

// freely adapted from https://github.com/mariusandra/pigeon-marker/blob/master/src/index.js
export const MapMarker: React.FunctionComponent<Props> = React.memo(({ left, top }: Props) => {
    return (
        <MapMarkerIcon
            style={{
                position: 'absolute',
                left: left! - PIN_CENTER.x,
                top: top! - PIN_CENTER.y,
            }}
        />
    );
});
```

```ts
/// icons/index.ts
import MapMarkerIcon from '../../../../assets/icons/map-marker.svg';

export { MapMarkerIcon };
```

**Comment by xstable** [comment]
Would be awesome if the marker-component by default would be an SVG-Marker which will be able to use a given Color to change it by parameter.

**Comment by mariusandra** [comment]
I'd be happy to merge any PR that makes this package better! SVG markers sound like a great thing to add!

**Comment by xstable** [comment]
You can assign me to this ticket. 
**BTW**: Please also add the label "hacktoberfest" to this project... or at least add the label "hacktoberfest-accepted" if I send an PR
See: https://hacktoberfest.digitalocean.com/details#rules

**Comment by mariusandra** [comment]
@xstable go for it!

**Comment by xstable** [comment]
On my map, it works just fine.
BTW: I've fixed an issue with the hover-color. It was switched.
![zoom](https://user-images.githubusercontent.com/1778068/97741406-f62ce300-1ae2-11eb-94d7-b052a6e382c2.gif)

**Comment by mariusandra** [comment]
pigeon-maps 0.17 is now out that includes a svg `<Marker />` component, deprecating this library. One of the props it has is `color`, resolving this issue.
